spring:
  cloud:
    gateway:
      routes:
      - predicates:
        - Path=/hello
        uri: "https://hello.apps.nonprod.us-east-1.aws.pcf.mapfreusa.com/greeting/english"
      - predicates:
        - Path=/hola
        uri: "https://hello.apps.nonprod.us-east-1.aws.pcf.mapfreusa.com/greeting/spanish"
      - predicates:
        - Path=/bonjour
        uri: "https://hello.apps.nonprod.us-east-1.aws.pcf.mapfreusa.com/greeting/french"
